name: Deploy static MkDocs pages
on:
  push:
    branches: [ main ]

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Trust Git workspace directory
        run: git config --global --add safe.directory /github/workspace
      - name: Deploy MkDocs pages
        if: startsWith(github.repository, 'osg-htc/')
        uses: docker://squidfunk/mkdocs-material
        with:
          args: >-
            gh-deploy
            --verbose
